### PR TITLE
Fixing Entrypoint

### PR DESCRIPTION
**Pull request by alegradi**
Closes https://github.com/ukfast/certbot-dns-safedns/issues/10

- Modified the Entrypoint to allow for other subcommands to be passed in
- Rewrote the Readme to be about the usage of the Docker container with some relevant info about the plugin

### CODE REVIEW

**Comment by alegradi** [comment]
@miff2000 Let me know what you think about the changes, especially the Readme. To me it makes more sense that this is about the usage of the Dockerfile, but that's only my opinion.

**Comment by alegradi** [comment]
Since we use the same repo for the plugin and the docker image based off it I've only extended the README. This way it has clear instruction on how to use the image and the plugin information is left intact.

**Comment by miff2000** [comment]
Looks good to me. I've made a couple of amends to that too. Are you happy with those changes?

**Comment by alegradi** [comment]
LGTM! 
Thanks for the spruce up.

**Pull request merged**
